name: Deploy AOSP Mirror Git Server to GCP

on:
  workflow_dispatch: # Manual trigger

jobs:
  terraform:
    runs-on: ubuntu-latest # github's runner
    env: 
      GOOGLE_CREDENTIALS: ${{ secrets.GCP_QL_SA_KEY }}
      TF_VAR_backend_bucket_name: ${{ vars.GCP_BUCKET_NAME }}
      TF_VAR_project_id: ${{ vars.GCP_PROJECT_ID }}
      TF_VAR_region: ${{ vars.GCP_REGION }}
      TF_VAR_mirror_git_server_password: ${{ secrets.GIT_SERVER_PASSWORD }}
    steps:
      # Get the terraform code from this repo onto the runner
      - name: Checkout repo 
        uses: actions/checkout@v3

      # Install TF on runner
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.6
      
      # Initialise TF with remote backend
      - name: Terraform init
        working-directory: ./terraform
        run: terraform init -backend-config="bucket='${{vars.GCP_BUCKET_NAME }}'"

      - name: Terraform plan
        working-directory: ./terraform
        run: terraform plan -out=tfplan
      
      - name: Terraform apply
        working-directory: ./terraform
        run: terraform apply -auto-approve tfplan

      - name: Get Mirror LB external IP
        id: get_mirror_lb_ip
        working-directory: ./terraform
        run: |
          echo "mirror_lb_ip=$(terraform output -raw lb_static_ip)" >> "$GITHUB_OUTPUT"

      - name: VM Health Check post deployment
        run: |
          echo "Waiting for VM to boot and complete startup scripts..."
          for i in {1..10}; do
            if curl --fail http://${{ steps.get_mirror_lb_ip.outputs.mirror_lb_ip }}/health; then
              echo "VM is healthy!"
              exit 0
            else
              echo "Attempt $i: VM Not healthy yet, retrying in 30s..."
              sleep 30
            fi
          done
          echo "VM failed to become healthy in time."
          exit 1
          
        