name: Deploy AOSP Mirror Git Server to GCP

on:
  workflow_dispatch: # Manual trigger

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest # github's runner
    env:
      TF_VAR_backend_bucket_name: ${{ vars.GCP_BUCKET_NAME }}
      TF_VAR_project_id: ${{ vars.GCP_PROJECT_ID }}
      TF_VAR_region: ${{ vars.GCP_REGION }}
      TF_VAR_gh_repo: "github.com/${{ github.repository }}.git"
      TF_VAR_gh_repo_pat: ${{ secrets.GH_REPO_PAT }}
      TF_VAR_mirror_git_server_password: ${{ secrets.GIT_SERVER_PASSWORD }}
    steps:
      # Get the terraform code from this repo onto the runner
      - name: Checkout repo 
        uses: actions/checkout@v3
      
      # Auth this WF with GCP
      - name: Authenticate to GCP using WIF
        id: auth
        uses: google-github-actions/auth@v2
        with:
          token_format: access_token
          workload_identity_provider: ${{ vars.GCP_WIF_PROVIDER }}
          service_account: ${{ vars.GCP_SA_EMAIL }}

      # Install TF on runner
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.6
      
      # Initialise TF with remote backend
      - name: Terraform init
        working-directory: ./terraform
        run: terraform init -backend-config="bucket=${{vars.GCP_BUCKET_NAME }}"

      - name: Terraform plan
        working-directory: ./terraform
        run: terraform plan -out=tfplan
      
      - name: Terraform apply
        id: terraform_apply
        working-directory: ./terraform
        run: terraform apply -auto-approve tfplan
      
      - name: Mirror LB Backend Service Health Check
        working-directory: ./scripts
        env:
          BACKEND_SERVICE_NAME: ${{ steps.terraform_apply.outputs.lb_backend_service_name }}
        run: bash lb-backend-health-check.sh

      - name: Mirror Liveness Check
        working-directory: ./scripts
        env:
          MIRROR_LB_IP: ${{ steps.terraform_apply.outputs.lb_static_ip }}
        run: bash liveness-check.sh